@messageId =ade0445a-78ef-49f2-8589-ab5581f6db42
@tagId=0219fbfa-ad4c-4c4d-9ceb-5019f87b23f3
@token=eyJhbGciOiJSUzI1NiIsImtpZCI6IjMzNzY4NjI4MzYyNTI3NDAzMSIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL21lc3NhZ2VwbHVzLThpdmRncS51czEueml0YWRlbC5jbG91ZCIsInN1YiI6IjMzNzY4NjI4MzA1NTM3Mjk3NSIsImF1ZCI6WyIzMzc2ODY3MDY0Mjc4Mjg5MTEiLCIzMzc2OTE2MTQ4NzA4MzY4MzgiLCIzMzc2ODY2MDg0OTkyMTkxMTkiXSwiZXhwIjoxNzU5Njg5NDY0LCJpYXQiOjE3NTkyNTc0NjQsIm5iZiI6MTc1OTI1NzQ2NCwiY2xpZW50X2lkIjoiMzM3NjkxNjE0ODcwODM2ODM4IiwianRpIjoiVjJfMzQwMTc3Mjg4NjcyODY5MDgwLWF0XzM0MDE3NzI4ODY3MjkzNDYxNiJ9.Sz8QZqSIkrbD4JniYsqLkBzer6A2GtFVZ7EIDCSnv_ZSXogSGnFbNloYU5L6L5o1YiPvuZUQEUH5rvgX4oXTRCGa3fSAzHGOSGH18cYuRmcED5wwR7HkzrBwZeg4p3C44Rx2mnbrMPNKFiccafqhjgJsGPIbx5wI_xWHNI7ZNCUYFQpxHTrEhg-VAcRPp7OdWxYQfm5Ws-iqATiIBx5hdifAY6b0uPhuauNnziTz3pNoM7O3-oFe_rjcrf3Jc8OAZjA5htTRq1uEFdZKxbQ40gSfaSaC2fL8FymukxQCScDBo0Pmh8lGFjUfZX45AcQ31gjuxU_HyEYKFc-U6U3jkw

### list all messages
GET {{host}}/api/templates?paged=false
Authorization: Bearer {{token}}

### list messages that have all tags
GET {{host}}/api/templates?paged=false&tagNames=WELCOME&tagNames=INFO
Authorization: Bearer {{token}}

### list all messages (paged)
GET {{host}}/api/templates
Authorization: Bearer {{token}}

### list messages that have all tags (paged)
GET {{host}}/api/templates?tagNames=WELCOME&tagNames=INFO
Authorization: Bearer {{token}}

### create message
POST {{host}}/api/templates
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "DELETE THIS",
  "bodyPt": "Obrigado por sua preferencia",
  "bodyEn": "Thanks for choosing us!"
}

### update message
PUT {{host}}/api/templates/{{messageId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "ThankYou10",
  "bodyPt": "Mensagem completamente nova",
  "bodyEn": "Completely new message"
}

#### delete message
DELETE {{host}}/api/templates/{{messageId}}
Authorization: Bearer {{token}}

### list tags
GET {{host}}/api/tags
Authorization: Bearer {{token}}

### create tag
POST {{host}}/api/tags
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "GOODBYE"
}

#### delete tag
DELETE {{host}}/api/tags/{{tagId}}
Authorization: Bearer {{token}}

### link a tag
POST {{host}}/api/templates/{{messageId}}/tags/{{tagId}}
Authorization: Bearer {{token}}

### unlink a tag
DELETE {{host}}/api/templates/{{messageId}}/tags/{{tagId}}
Authorization: Bearer {{token}}

####
GET {{host}}/actuator/health

#### authorisation flow (device code)
POST https://messageplus-8ivdgq.us1.zitadel.cloud/oauth/v2/device_authorization?client_id=337691614870836838&scope=pearce.oliver@gmail.com

####
POST https://messageplus-8ivdgq.us1.zitadel.cloud/oauth/v2/token?grant_type=urn:ietf:params:oauth:grant-type:device_code&device_code=IMPP3PKIF_lWWYJej0sU5g&client_id=337691614870836838
Content-Type:application/x-www-form-urlencoded