@messageId = 0fffa1dd-af7d-4bad-afc2-f75bc0867da2

GET {{host}}/api/templates

###
POST {{host}}/api/templates
Content-Type: application/json

{
  "name": "ThankYou5",
  "body": "Thanks for choosing us added message!"
}

###
PUT {{host}}/api/templates/{{messageId}}
Content-Type: application/json

{
  "name": "New Title",
  "body": "Completely new message"
}

####
DELETE {{host}}/api/templates/{{messageId}}

####
GET {{host}}/actuator/health