create table if not exists message_template (
    id bigint generated by default as identity primary key,
    title varchar(120) not null unique,
    body clob not null,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp
    );